<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\DataLooMStudio.SharedKernel\DataLooMStudio.SharedKernel.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\DataLooMStudio.Infrastructure\DataLooMStudio.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Runtime\DataLooMStudio.Runtime\DataLooMStudio.Runtime.csproj" />
    <ProjectReference Include="..\..\Runtime\DataLooMStudio.Runtime.Persistence\DataLooMStudio.Runtime.Persistence.csproj" />
  </ItemGroup>

</Project>
